#!/usr/bin/env python3
"""Tiny CommonJS bundler (no dependency, Python 3.8+).

Bundles an entry file and every module it require()s into one classic script,
for runtimes that cannot load ES modules / local files (Adobe UXP) or that run
sandboxed without require (Electron renderer).

Resolution rules:
  require('./x') / require('../x')  -> relative to the requiring file
  require('core/x')                 -> <repo>/core/x
  anything else                     -> left to the runtime's own require()
                                       (e.g. 'uxp', 'premierepro'), if any.

Usage: bundle.py <entry.js> <output.js>
"""

import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REQUIRE_RE = re.compile(r"""\brequire\(\s*(['"])([^'"]+)\1\s*\)""")


def resolve(spec, from_file):
    if spec.startswith('./') or spec.startswith('../'):
        base = os.path.normpath(os.path.join(os.path.dirname(from_file), spec))
    elif spec == 'core' or spec.startswith('core/'):
        base = os.path.join(REPO, spec)
    else:
        return None  # external module
    for candidate in (base, base + '.js', os.path.join(base, 'index.js')):
        if os.path.isfile(candidate):
            return os.path.abspath(candidate)
    raise SystemExit(f"bundle: cannot resolve '{spec}' from {from_file}")


def strip_comments(src):
    # Good enough to avoid picking up require() mentioned in comments.
    src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)
    return re.sub(r'(^|[^:\'"\\])//[^\n]*', r'\1', src)


def collect(entry):
    modules = {}
    order = []
    stack = [os.path.abspath(entry)]
    while stack:
        path = stack.pop()
        if path in modules:
            continue
        with open(path, encoding='utf-8') as f:
            src = f.read()
        deps = {}
        for m in REQUIRE_RE.finditer(strip_comments(src)):
            spec = m.group(2)
            target = resolve(spec, path)
            if target:
                deps[spec] = target
                stack.append(target)
        modules[path] = (src, deps)
        order.append(path)
    return modules, order


def module_id(path):
    return os.path.relpath(path, REPO).replace(os.sep, '/')


def bundle(entry, output):
    modules, order = collect(entry)
    parts = [
        '/* Generated by scripts/bundle.py — do not edit. */',
        '(function () {',
        '"use strict";',
        'var defs = {}, cache = {};',
        'var hostRequire = typeof require === "function" ? require : null;',
        'function load(id) {',
        '  if (cache[id]) return cache[id].exports;',
        '  var module = { exports: {} };',
        '  cache[id] = module;',
        '  var def = defs[id];',
        '  def[0].call(module.exports, module, module.exports, function (name) {',
        '    var target = def[1][name];',
        '    if (target) return load(target);',
        '    if (hostRequire) return hostRequire(name);',
        '    throw new Error("Module not available: " + name);',
        '  });',
        '  return module.exports;',
        '}',
    ]
    for path in order:
        src, deps = modules[path]
        dep_map = {spec: module_id(t) for spec, t in deps.items()}
        parts.append(f'defs[{json.dumps(module_id(path))}] = [function (module, exports, require) {{')
        parts.append(src)
        parts.append(f'\n}}, {json.dumps(dep_map)}];')
    parts.append(f'load({json.dumps(module_id(os.path.abspath(entry)))});')
    parts.append('})();')
    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    with open(output, 'w', encoding='utf-8') as f:
        f.write('\n'.join(parts) + '\n')
    print(f'bundle: {module_id(os.path.abspath(entry))} + {len(order) - 1} modules -> {os.path.relpath(output, REPO)}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    bundle(sys.argv[1], sys.argv[2])
